namespace ContractGenerator.Tests;

public class ContractGeneratorTests
{
    private static FileStream GetInputStream(string testcaseName)
    {
        return File.Open($"testcases/{testcaseName}/descriptor.bin", FileMode.Open);
    }

    [Fact]
    public void TestGenerate_NoErrors()
    {
        var stdin = GetInputStream("helloworld");
        var fileDescriptors = FileDescriptorSetLoader.Load(stdin);
        var options = new List<Tuple<string, string>> { new("", "") };
        var response = ContractGenerator.Generate(fileDescriptors, new GeneratorOptions
        {
            GenerateContract = true,
            GenerateEvent = true
        });

        Assert.Single(response.File);
        Assert.Equal("Contract.c.cs", response.File[0].Name);
        Assert.True(response.File[0].HasContent);

        const string expectedContractContents = @"// <auto-generated>

//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.HelloWorld {

#region Events
  public partial class UpdatedMessage : aelf::IEvent<UpdatedMessage>
  {
    public global::System.Collections.Generic.IEnumerable<UpdatedMessage> GetIndexed()
    {
      return new List<UpdatedMessage>
      {
      };
    }

    public UpdatedMessage GetNonIndexed()
    {
      return new UpdatedMessage
      {
        Value = Value,
      };
    }
  }

  #endregion

  public static partial class HelloWorldContainer
  {
    static readonly string __ServiceName = ""HelloWorld"";
    #region Marshallers
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, $response$> __Method_Update = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        ""Update"",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, $response$> __Method_Read = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        ""Read"",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AElf.Contracts.HelloWorld.ContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Contracts.HelloWorld.ContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of HelloWorldBase</summary>
    public abstract partial class HelloWorldBase : AElf.Sdk.CSharp.CSharpSmartContract<AElf.Contracts.HelloWorld.HelloWorldState>
    {
      public abstract global::Google.Protobuf.WellKnownTypes.Empty Update(global::Google.Protobuf.WellKnownTypes.StringValue input);
      public abstract global::Google.Protobuf.WellKnownTypes.StringValue Read(global::Google.Protobuf.WellKnownTypes.Empty input);
    }

    public static aelf::ServerServiceDefinition BindService(HelloWorldBase serviceImpl)
    {
      return aelf::ServerServiceDefinition.CreateBuilder()
          .AddDescriptors(Descriptors)
          .AddMethod(__Method_Update, serviceImpl.Update).Build();
          .AddMethod(__Method_Read, serviceImpl.Read).Build();
    }

  }

}
#endregion

";

        Assert.Equal(expectedContractContents, response.File[0].Content);
    }
}
